### PR TITLE
Update pkg.ts

### PR DESCRIPTION
**Pull request by o-az**
https://pnpm.io/cli/dlx

**Describe the pull request**

make pnpm exec work

**Why**

the following doesn't work
```sh
pnpm graphqurl https://spacex-production.up.railway.app --introspect
```
whereas this works
```sh
pnpm dlx graphqurl https://spacex-production.up.railway.app --introspect
```

**How**

How were these changes implemented?

**Screenshots**

If applicable, add screenshots to help explain what is being modified.

### CODE REVIEW

**Review by HiDeoo — COMMENTED** [review]
Thanks for your contribution :raised_hands:

I think the current behavior is correct as it's matching the [`pnpm exec`](https://pnpm.io/cli/exec) one which says:

> The exec part is actually optional when the command is not in conflict with a builtin pnpm command […]

Altho, I think we could add a totally new command type, e.g. `dlx`? What do you think?

**Comment by o-az** [comment]
> Thanks for your contribution 🙌
> 
> I think the current behavior is correct as it's matching the [`pnpm exec`](https://pnpm.io/cli/exec) one which says:
> 
> > The exec part is actually optional when the command is not in conflict with a builtin pnpm command […]
> 
> Altho, I think we could add a totally new command type, e.g. `dlx`? What do you think?

I think that makes sense! Since `pnpm` has 

`pnpm`, `pnpm run`,
`pnpm exec`,
`pnpm dlx`

**Comment by o-az** [comment]
although just to be clear @HiDeoo, `pnpm exec` is not the same as `npx` since it doesn't attempt to install the package.

**Comment by HiDeoo** [comment]
> although just to be clear @HiDeoo, `pnpm exec` is not the same as `npx` since it doesn't attempt to install the package.

This is the case altho based on ["`npx` vs `npm exec`"](https://docs.npmjs.com/cli/v10/commands/npx#npx-vs-npm-exec), I've seen people mostly interchanging them but prefering the `npx` argument parsing logic.

**Comment by o-az** [comment]
currently with this setup:

```jsx
<PackageManagers
  pkg="jsr"
  type="exec"
  frame="none"
  args="add @union/client"
  pkgManagers={['pnpm']}
/>
```

it renders:

```sh
pnpm jsr add @union/client
```

which when ran results in:

```sh
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  Command "jsr" not found
```

whereas `pnpm dlx jsr add @union/client` works as expected.

You suggest I update the pr and add a new command for `pnpm dlx`?

**Comment by HiDeoo** [comment]
I think this is what we agreed on and still makes sense. I would be up to the user to use the appropriate syntax that will work based on the situation, we cannot predict what is the desired behavior in this case if I'm not missing something.

**Comment by HiDeoo** [comment]
Thanks to https://github.com/HiDeoo/starlight-package-managers/pull/15, the version [0.8.0](https://github.com/HiDeoo/starlight-package-managers/releases/tag/v0.8.0) now includes the [`dlx` command type](https://starlight-package-managers.vercel.app/usage/#dlx) :tada:

**Pull request closed without merging**
